In [1]:
import torch

# PyTorch version

In [2]:
torch.__version__

'2.13.0+cu130'

# Create a tensor

In [3]:
data = [[3, 2],[3, 1]]  # This is called a nested list.

In [4]:
data

[[3, 2], [3, 1]]

In [5]:
x_data = torch.tensor(data)

In [6]:
x_data

tensor([[3, 2],
        [3, 1]])

# From another tensor

In [7]:
torch.ones_like(x_data)

tensor([[1, 1],
        [1, 1]])

In [8]:
torch.rand_like(x_data, dtype=torch.float)

tensor([[0.3456, 0.2281],
        [0.4356, 0.4605]])

# Create from shape

In [9]:
shape = [4, 5]
random_tensor = torch.rand(shape)

In [10]:
random_tensor

tensor([[0.8005, 0.8308, 0.2580, 0.9039, 0.2247],
        [0.7856, 0.4891, 0.8103, 0.2858, 0.0164],
        [0.1974, 0.4994, 0.2687, 0.2083, 0.9052],
        [0.0634, 0.2244, 0.4071, 0.6586, 0.8780]])

In [11]:
torch.ones(shape)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [12]:
torch.zeros(2,2)

tensor([[0., 0.],
        [0., 0.]])

In [13]:
torch.zeros(2,2,2)

tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])

# Attributes of a Tensor

In [14]:
random_tensor.shape

torch.Size([4, 5])

In [15]:
dir(random_tensor)

['H',
 'T',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__div__',
 '__dlpack__',
 '__dlpack_c_exchange_api__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__idiv__',
 '__ifloordiv__',
 '__ilshift__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__long__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__r

In [16]:
random_tensor.dtype

torch.float32

In [17]:
random_tensor.device


device(type='cpu')

In [18]:
random_tensor.ndim

2

# Random seed

In [19]:
torch.manual_seed(12345)
random_tensor = torch.randn(shape)
random_tensor


tensor([[-1.4798,  0.4873, -3.0128,  0.4439, -1.0148],
        [-0.5429,  0.4307, -1.9257, -0.2145, -1.2620],
        [-0.1282, -0.3737,  0.2058, -0.9300,  0.1142],
        [-0.4450,  0.5224,  0.6058,  0.7472,  0.1542]])

# Indexing and slicing

In [20]:
random_tensor[0,0]

tensor(-1.4798)

In [21]:
random_tensor[0, 1]

tensor(0.4873)

In [22]:
random_tensor[-1,-1]

tensor(0.1542)

In [23]:
random_tensor[0]

tensor([-1.4798,  0.4873, -3.0128,  0.4439, -1.0148])

In [24]:
random_tensor[1]

tensor([-0.5429,  0.4307, -1.9257, -0.2145, -1.2620])

In [25]:
random_tensor[-1]

tensor([-0.4450,  0.5224,  0.6058,  0.7472,  0.1542])

In [26]:
random_tensor[-2]

tensor([-0.1282, -0.3737,  0.2058, -0.9300,  0.1142])

In [27]:
random_tensor[:, 0]

tensor([-1.4798, -0.5429, -0.1282, -0.4450])

In [28]:
random_tensor[:, 1]

tensor([ 0.4873,  0.4307, -0.3737,  0.5224])

In [29]:
random_tensor[..., -1]

tensor([-1.0148, -1.2620,  0.1142,  0.1542])

In [30]:
random_tensor[:, 0:1]

tensor([[-1.4798],
        [-0.5429],
        [-0.1282],
        [-0.4450]])

In [31]:
random_tensor[:, 1:2]

tensor([[ 0.4873],
        [ 0.4307],
        [-0.3737],
        [ 0.5224]])

# Setting tensor elements

In [32]:
random_tensor

tensor([[-1.4798,  0.4873, -3.0128,  0.4439, -1.0148],
        [-0.5429,  0.4307, -1.9257, -0.2145, -1.2620],
        [-0.1282, -0.3737,  0.2058, -0.9300,  0.1142],
        [-0.4450,  0.5224,  0.6058,  0.7472,  0.1542]])

In [33]:
random_tensor[2,2] = 99
random_tensor

tensor([[-1.4798,  0.4873, -3.0128,  0.4439, -1.0148],
        [-0.5429,  0.4307, -1.9257, -0.2145, -1.2620],
        [-0.1282, -0.3737, 99.0000, -0.9300,  0.1142],
        [-0.4450,  0.5224,  0.6058,  0.7472,  0.1542]])

In [34]:
random_tensor[1] = 0
random_tensor

tensor([[-1.4798,  0.4873, -3.0128,  0.4439, -1.0148],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
        [-0.1282, -0.3737, 99.0000, -0.9300,  0.1142],
        [-0.4450,  0.5224,  0.6058,  0.7472,  0.1542]])

In [35]:
random_tensor.fill_diagonal_(5)
random_tensor

tensor([[ 5.0000,  0.4873, -3.0128,  0.4439, -1.0148],
        [ 0.0000,  5.0000,  0.0000,  0.0000,  0.0000],
        [-0.1282, -0.3737,  5.0000, -0.9300,  0.1142],
        [-0.4450,  0.5224,  0.6058,  5.0000,  0.1542]])

How could we figure out "fill_diagonal_" on our own?

Simply search it online: "How to set the diagonal of a torch tensor".

At the end of this notebook will be a challenge based on this.

In [36]:
[i for i in dir(random_tensor) if 'diagonal' in i]  # This is list comprehension with a condition.

['diagonal', 'diagonal_scatter', 'fill_diagonal_']

In [37]:
random_tensor.diagonal()

tensor([5., 5., 5., 5.])

# Permute/transpose

In [38]:
random_tensor.transpose(1, 0)

tensor([[ 5.0000,  0.0000, -0.1282, -0.4450],
        [ 0.4873,  5.0000, -0.3737,  0.5224],
        [-3.0128,  0.0000,  5.0000,  0.6058],
        [ 0.4439,  0.0000, -0.9300,  5.0000],
        [-1.0148,  0.0000,  0.1142,  0.1542]])

In [39]:
random_tensor.permute(1, 0)

tensor([[ 5.0000,  0.0000, -0.1282, -0.4450],
        [ 0.4873,  5.0000, -0.3737,  0.5224],
        [-3.0128,  0.0000,  5.0000,  0.6058],
        [ 0.4439,  0.0000, -0.9300,  5.0000],
        [-1.0148,  0.0000,  0.1142,  0.1542]])

In [40]:
random_tensor.T

tensor([[ 5.0000,  0.0000, -0.1282, -0.4450],
        [ 0.4873,  5.0000, -0.3737,  0.5224],
        [-3.0128,  0.0000,  5.0000,  0.6058],
        [ 0.4439,  0.0000, -0.9300,  5.0000],
        [-1.0148,  0.0000,  0.1142,  0.1542]])

# Joining tensors

In [41]:
a = torch.ones([5, 2])
a

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])

In [42]:
b = torch.zeros([5, 2])
b

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])

In [43]:
torch.cat([a, b], dim=1)


tensor([[1., 1., 0., 0.],
        [1., 1., 0., 0.],
        [1., 1., 0., 0.],
        [1., 1., 0., 0.],
        [1., 1., 0., 0.]])

In [44]:
torch.cat([a, b, a], dim=0)


tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])

In [45]:
c = torch.stack([a, b, a], dim=0)
c

tensor([[[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]]])

In [46]:
c.shape

torch.Size([3, 5, 2])

# Basic arithmetic operations

In [47]:
a = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float32)
b = torch.tensor([[7, 8, 9], [10, 11, 12]], dtype=torch.float32)

In [48]:
a + b

tensor([[ 8., 10., 12.],
        [14., 16., 18.]])

In [49]:
a - b

tensor([[-6., -6., -6.],
        [-6., -6., -6.]])

In [50]:
a / b

tensor([[0.1429, 0.2500, 0.3333],
        [0.4000, 0.4545, 0.5000]])

# Matrix multiplication

In [51]:
a @ b.T

tensor([[ 50.,  68.],
        [122., 167.]])

In [52]:
a.matmul(b.T)

tensor([[ 50.,  68.],
        [122., 167.]])

# Elementwise product

In [53]:
a * b

tensor([[ 7., 16., 27.],
        [40., 55., 72.]])

In [54]:
a.mul(b)

tensor([[ 7., 16., 27.],
        [40., 55., 72.]])

# Pooling

In [55]:
a

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [56]:
a.sum()

tensor(21.)

In [57]:
a.sum().item()

21.0

In [58]:
a.mean()

tensor(3.5000)

In [59]:
a.sum(dim=0)

tensor([5., 7., 9.])

In [60]:
a.sum(dim=1)

tensor([ 6., 15.])

# Challenge

In the cell below, compute a 5x5 identity matrix (i.e., a an identity matrix with 5 rows and 5 columns).

There are multiple ways to do this; look through the notebook for hints.